<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ParsedownExtra' => array($vendorDir . '/erusev/parsedown-extra'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'AlgoliaSearch' => array($vendorDir . '/algolia/algoliasearch-client-php/src'),
);
